=== propbank/propbank-frames/dtds/v3.4/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (r | p | v | n | j | l | x| m | d | f) #REQUIRED>


<!--
  pos = Part of Speech
  
  Can take the following values:

  r = Adverb
  p = Preposition
  v = Verb
  n = Noun
  j = Adjective
  l = (MISSING IDK)
  x = (MISSING IDK)
  m = (MISSING IDK)

-->


<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)
    
    #
    # Function tags for spatial arguments
    #
    SE1  first thing (UNVERIFIED)
    SE2  second thing (UNVERIFIED)    
    SE3  third thing (UNVERIFIED)
    SE4  fourth thing (UNVERIFIED)
    SE5  fifth thing (UNVERIFIED)    
    SE6  sixth thing (UNVERIFIED)    

    SCL  Scale (UNVERIFIED)

    DOM  Domain (UNVERIFIED)

    #
    # added from the spatial relations ontology
    #
    # https://docs.google.com/spreadsheets/d/1b_CJUsyGptG0RtZQ5qnuJjF0wHKyiahLJ83RhHRwgCE/edit#gid=154847108
    #
    ANC  anchor
    ANC1 first anchor
    ANC2 second anchor
    
    ANG angle

    AXS  axis
    AXSp perpendicular axis
    AXSc central axis
    AXS1 axis of spatial entity 1
    AXS2 axis of spatial entity 2

    WHL  whole spatial entity
    
    SEQ  sequence

    PSN  position
    #

    #
    # Not sure to which subgroup these balong
    #
    SET
    SRC  Source (UNVERIFIED)
    PRT
    



-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( ANC | ANC1 | ANC2 | ANG | DOM | AXS | AXSp | AXSc | AXS1 | AXS2 | WHL | SEQ | SET | SRC | PRT | SE1 | SE2 | SE3 | SE4 | SE5 | SE6 | SCL | PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!-- Adding a new element to distinguish propbank example from amr example (UNVERIFIED) -->
<!ELEMENT propbank (arg|rel|note)*>

<!ELEMENT amr (#PCDATA)>
<!ATTLIST amr
  version CDATA #IMPLIED>

<!ELEMENT example (note?, text, (propbank | amr | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  type ( ARG0 | ARG1 | ARG2 | ARG3 | ARG4 | ARG5 | ARG6 | ARG7 | C-ARG0 | C-ARG1 | C-ARG2 | C-ARG3 | C-ARG4 | C-ARG5 | C-ARG6 | C-ARG7 | R-ARG0 | R-ARG1 | R-ARG2 | R-ARG3 | R-ARG4 | R-ARG5 | R-ARG6 | R-ARG7 | ARGM-ADJ | ARGM-ADV | ARGM-CAU | ARGM-COM | ARGM-DIR | ARGM-DIS | ARGM-DSP | ARGM-EXT | ARGM-GOL | ARGM-LOC | ARGM-LVB | ARGM-MNR | ARGM-MOD | ARGM-NEG | ARGM-PNC | ARGM-PRD | ARGM-PRP | ARGM-PRR | ARGM-PRX | ARGM-REC | ARGM-TMP | ARGM-CXN | C-ARGM-ADJ | C-ARGM-ADV | C-ARGM-CAU | C-ARGM-COM | C-ARGM-DIR | C-ARGM-DIS | C-ARGM-DSP | C-ARGM-EXT | C-ARGM-LOC | C-ARGM-MNR | C-ARGM-MOD | C-ARGM-NEG | C-ARGM-PRP | C-ARGM-TMP | C-ARGM-CXN | R-ARGM-ADV | R-ARGM-CAU | R-ARGM-COM | R-ARGM-DIR | R-ARGM-EXT | R-ARGM-GOL | R-ARGM-LOC | R-ARGM-MNR | R-ARGM-MOD | R-ARGM-PNC | R-ARGM-PRD | R-ARGM-PRP | R-ARGM-TMP) #REQUIRED
  start CDATA #REQUIRED
  end CDATA #REQUIRED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== propbank/propbank-frames/frames/peri.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="peri">
    <roleset id="peri.01" name="occurring in the time around a particular event">
      <aliases>
        <alias pos="f">peri</alias>
        <alias pos="f">peri-</alias>
      </aliases>
      <roles>
        <role descr="thing occurring around the time of ARG2" f="PPT" n="1"/>
        <role descr="reference event" f="PPT" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="-"/>
        <usage resource="PropBank" version="3.4" inuse="-"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="-"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="-"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="-"/>
      </usagenotes>
      <lexlinks/>
      <example name="peri-f, both args" src="THYME-colon-mod">
        <text>They will see her for management of her diabetes perioperatively .</text>
        <propbank/>
        <amr version="THYME 1.0">
          (s2 / see-09
            :ARG0 (t / they)
            :ARG1 s
            :ARG2 (m / manage-01
              :ARG0 t
              :ARG1 (d / disease-disorder :name (n / name :op1 "diabetes")
                :poss (s / she))
              :ARG1-of (p / peri-01
                :ARG2 (o / operate-02
                  :ARG2 s)))) 
        </amr>
      </example>
      <note>NOTES: Added for THYME-AMR. A closed list of prefix frames (intra.01, peri.01, post.05, pre.01) were created to resolve temporal conflicts generated in the merged THYME AMR-THYME 2 annotations. They are to be used in tandem with frames that represent the terms' roots, but only when they convey temporal information. They should not be used for spatial senses (like "perirectal") or other non-temporal senses.</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/journey.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="journey">
    <roleset id="journey.01" name="travel">
      <aliases>
        <alias pos="v">journey</alias>
        <alias pos="n">journey</alias>
      </aliases>
      <roles>
        <role descr="traveller" f="PAG" n="0">
          <rolelinks>
            <rolelink class="run-51.3.2-1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Travel" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="run-51.3.2-1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="Transportperson" confidence="0.1" resource="ERE" src="reo-expansion" version="rich"/>
        <lexlink class="run-51.3.2-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="get out of town" src="">
        <text>Giffen had already urged him to journey south , if only for a few days to clear up matters .</text>
        <propbank>
          <rel relloc="6">journey</rel>
          <arg type="ARG0" start="4" end="4">him</arg>
          <arg type="ARGM-DIR" start="7" end="7">south</arg>
          <arg type="ARGM-ADV" start="9" end="14">if only for a few days</arg>
          <arg type="ARGM-PNC" start="15" end="18">to clear up matters</arg>
        </propbank>
      </example>
      <example name="arg 0 and debateable dir (could be gol too)" src="">
        <text>His hometown journey</text>
        <propbank>
          <rel relloc="2">journey</rel>
          <arg type="ARG0" start="0" end="0">His</arg>
          <arg type="ARGM-DIR" start="1" end="1">hometown</arg>
        </propbank>
      </example>
      <note>JOURNEY-V NOTES: Framed by Ben. (from journey.01-v)</note>
      <note>JOURNEY-N NOTES: Based on sentences in wsj. Comparison to journey.01. VN class run-51.3.2. Framed by Katie. (from journey.01-n)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/unteach.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="unteach">
    <roleset id="unteach.01" name="make forget learning">
      <aliases>
        <alias pos="v">unteach</alias>
      </aliases>
      <roles>
        <role descr="unteacher" f="PAG" n="0"/>
        <role descr="subject" f="PPT" n="1"/>
        <role descr="(former) student" f="GOL" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="unteach-v: transitive" src="">
        <text>`` And God help anyone who tries to unteach you '' ! ! Grumbled Michelangelo ; ; yet he knew that he had nothing to grumble about , for Argiento made few demands on him .</text>
        <propbank>
          <rel relloc="8">unteach</rel>
          <arg type="R-ARG0" start="4" end="4">anyone</arg>
          <arg type="ARG0" start="5" end="5">who</arg>
          <arg type="ARG2" start="9" end="9">you</arg>
        </propbank>
      </example>
      <note>UNTEACH-V NOTES: frames created by Ben. c.f. 'teach'. No Vncls. (from unteach.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/anticipate.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="anticipate">
    <roleset id="anticipate.01" name="expect">
      <aliases>
        <alias pos="n">anticipation</alias>
        <alias pos="v">anticipate</alias>
      </aliases>
      <roles>
        <role descr="anticipater" f="PAG" n="0">
          <rolelinks>
            <rolelink class="conjecture-29.5-1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
            <rolelink class="conjecture-29.5-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
          </rolelinks>
        </role>
        <role descr="thing anticipated" f="PPT" n="1">
          <rolelinks>
            <rolelink class="conjecture-29.5-1" resource="VerbNet" version="verbnet3.3">theme</rolelink>
            <rolelink class="conjecture-29.5-1" resource="VerbNet" version="verbnet3.4">theme</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Expectation" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="anticipate-v.1" confidence="0.1" resource="onsense" src="annot-overlap" version="on5">50</lexlink>
        <lexlink class="conjecture-29.5-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="active, light S as object" src="">
        <text>The documents also said that Cray Computer anticipates needing perhaps another $ 120 million in financing beginning next September .</text>
        <propbank>
          <rel relloc="7">anticipates</rel>
          <arg type="ARG0" start="5" end="6">Cray Computer</arg>
          <arg type="ARG1" start="8" end="18">needing perhaps another $ 120 million in financing beginning next September</arg>
        </propbank>
      </example>
      <example name="active, SBAR as object" src="">
        <text>But speculators , anticipating that Connecticut will approve a law permitting such interstate banking soon , immediately bid up shares of Connecticut banks on the news .</text>
        <propbank>
          <rel relloc="3">anticipating</rel>
          <arg type="ARG0" start="1" end="1">speculators</arg>
          <arg type="ARG1" start="4" end="14">that Connecticut will approve a law permitting such interstate banking soon</arg>
        </propbank>
      </example>
      <example name="passivized with extraction" src="">
        <text>John is anticipated to win the Nobel Prize .</text>
        <propbank>
          <rel relloc="2">anticipated</rel>
          <arg type="ARG1" start="3" end="7">to win the Nobel Prize</arg>
        </propbank>
      </example>
      <example name="with comparative" src="">
        <text>`` This is all emotion right now , and when emotion starts to run , it can run further than anyone anticipates , '' he said .</text>
        <propbank>
          <rel relloc="21">anticipates</rel>
          <arg type="ARG0" start="20" end="20">anyone</arg>
        </propbank>
      </example>
      <example name="arg 1" src="">
        <text>gleeful anticipation of getting a share of this market</text>
        <propbank>
          <rel relloc="1">anticipation</rel>
          <arg type="ARGM-MNR" start="0" end="0">gleeful</arg>
          <arg type="ARG1" start="2" end="8">of getting a share of this market</arg>
        </propbank>
      </example>
      <example name="Both args" src="">
        <text>His anticipation of the blow saved it from doing serious damage</text>
        <propbank>
          <rel relloc="1">anticipation</rel>
          <arg type="ARG0" start="0" end="0">His</arg>
          <arg type="ARG1" start="2" end="4">of the blow</arg>
        </propbank>
      </example>
      <note>ANTICIPATE-V NOTES: No verbnet entry. Comparison with 'expect' (from anticipate.01-v)</note>
      <note>ANTICIPATION-N NOTES: Added due to expansion of Nombank. Comparison to 'anticipate.01' No Vn or Fn classes. Framed by Katie. (from anticipation.01-n)</note>
      <note>Sometimes also with an empty Arg1 (trace only) (from anticipate.01-v)</note>
    </roleset>
    <roleset id="anticipate.02" name="come before">
      <aliases>
        <alias pos="v">anticipate</alias>
      </aliases>
      <roles>
        <role descr="thing coming before" f="PAG" n="0"/>
        <role descr="thing coming after" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Predate" confidence="0.0" resource="FrameNet" src="manual+strict-conv" version="UNK"/>
      </lexlinks>
      <example name="active" src="">
        <text>The downgrade anticipates completion of the IMA Holdings acquisition today , Moody 's said .</text>
        <propbank>
          <rel relloc="2">anticipates</rel>
          <arg type="ARG0" start="0" end="1">The downgrade</arg>
          <arg type="ARG1" start="3" end="9">completion of the IMA Holdings acquisition today</arg>
        </propbank>
      </example>
      <note>ANTICIPATE-V NOTES: These two senses are very close in meaning, but fortunately theframing is the same. (from anticipate.02-v)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/bloodwork.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="bloodwork">
    <roleset id="bloodwork.01" name="draw/test blood components">
      <aliases>
        <alias pos="n">blood_counts</alias>
        <alias pos="n">blood_work</alias>
        <alias pos="n">bloodwork</alias>
        <alias pos="n">blood_tests</alias>
      </aliases>
      <roles>
        <role descr="performer" f="PAG" n="0"/>
        <role descr="patient" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="-"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="-"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="blood_work-n" src="THYME-colon-mod">
        <text>Blood work obtained on November 3 , 2007 : Hemoglobin 8.1 .</text>
        <propbank>
          <rel relloc="0 1">Blood work</rel>
        </propbank>
        <amr version="THYME 1.0">
          (s / show-01 :implicit +
            :ARG0 (b / bloodwork-01
              :time (d / date-entity :month 11 :day 3 :year 2007))
            :ARG1 (h / have-value-91
              :ARG1 (a / anatomical-site :name (n / name :op1 "hemoglobin"))
              :ARG2 8.1))
        </amr>
      </example>
      <note>BLOODWORK NOTES: Added for THYME-AMR.</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/pg.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="pg">
    <roleset id="pg.01" name="parental guidance movie rating">
      <aliases>
        <alias pos="j">pg</alias>
      </aliases>
      <roles>
        <role descr="pg movie or entity" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <example name="PG-j" src="">
        <text>He lay on the ground while I looked up our class schedule on my iPad ! And he put his hand on my leg -LRB- below the knee ... this is PG after all -RRB- and I clasped his hand and he squeezed mine and we squeezed hands back and forth until I woke</text>
        <propbank>
          <rel relloc="31">PG</rel>
          <arg type="ARG1" start="29" end="29">this</arg>
          <arg type="ARGM-DIS" start="32" end="33">after all</arg>
        </propbank>
      </example>
      <note>PG-J NOTES: Added automatically by Julia. (from pg.01-j)</note>
    </roleset>
  </predicate>
</frameset>
