=== propbank/propbank-frames/dtds/v3.4/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (r | p | v | n | j | l | x| m | d | f) #REQUIRED>


<!--
  pos = Part of Speech
  
  Can take the following values:

  r = Adverb
  p = Preposition
  v = Verb
  n = Noun
  j = Adjective
  l = (MISSING IDK)
  x = (MISSING IDK)
  m = (MISSING IDK)

-->


<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)
    
    #
    # Function tags for spatial arguments
    #
    SE1  first thing (UNVERIFIED)
    SE2  second thing (UNVERIFIED)    
    SE3  third thing (UNVERIFIED)
    SE4  fourth thing (UNVERIFIED)
    SE5  fifth thing (UNVERIFIED)    
    SE6  sixth thing (UNVERIFIED)    

    SCL  Scale (UNVERIFIED)

    DOM  Domain (UNVERIFIED)

    #
    # added from the spatial relations ontology
    #
    # https://docs.google.com/spreadsheets/d/1b_CJUsyGptG0RtZQ5qnuJjF0wHKyiahLJ83RhHRwgCE/edit#gid=154847108
    #
    ANC  anchor
    ANC1 first anchor
    ANC2 second anchor
    
    ANG angle

    AXS  axis
    AXSp perpendicular axis
    AXSc central axis
    AXS1 axis of spatial entity 1
    AXS2 axis of spatial entity 2

    WHL  whole spatial entity
    
    SEQ  sequence

    PSN  position
    #

    #
    # Not sure to which subgroup these balong
    #
    SET
    SRC  Source (UNVERIFIED)
    PRT
    



-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( ANC | ANC1 | ANC2 | ANG | DOM | AXS | AXSp | AXSc | AXS1 | AXS2 | WHL | SEQ | SET | SRC | PRT | SE1 | SE2 | SE3 | SE4 | SE5 | SE6 | SCL | PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!-- Adding a new element to distinguish propbank example from amr example (UNVERIFIED) -->
<!ELEMENT propbank (arg|rel|note)*>

<!ELEMENT amr (#PCDATA)>
<!ATTLIST amr
  version CDATA #IMPLIED>

<!ELEMENT example (note?, text, (propbank | amr | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  type ( ARG0 | ARG1 | ARG2 | ARG3 | ARG4 | ARG5 | ARG6 | ARG7 | C-ARG0 | C-ARG1 | C-ARG2 | C-ARG3 | C-ARG4 | C-ARG5 | C-ARG6 | C-ARG7 | R-ARG0 | R-ARG1 | R-ARG2 | R-ARG3 | R-ARG4 | R-ARG5 | R-ARG6 | R-ARG7 | ARGM-ADJ | ARGM-ADV | ARGM-CAU | ARGM-COM | ARGM-DIR | ARGM-DIS | ARGM-DSP | ARGM-EXT | ARGM-GOL | ARGM-LOC | ARGM-LVB | ARGM-MNR | ARGM-MOD | ARGM-NEG | ARGM-PNC | ARGM-PRD | ARGM-PRP | ARGM-PRR | ARGM-PRX | ARGM-REC | ARGM-TMP | ARGM-CXN | C-ARGM-ADJ | C-ARGM-ADV | C-ARGM-CAU | C-ARGM-COM | C-ARGM-DIR | C-ARGM-DIS | C-ARGM-DSP | C-ARGM-EXT | C-ARGM-LOC | C-ARGM-MNR | C-ARGM-MOD | C-ARGM-NEG | C-ARGM-PRP | C-ARGM-TMP | C-ARGM-CXN | R-ARGM-ADV | R-ARGM-CAU | R-ARGM-COM | R-ARGM-DIR | R-ARGM-EXT | R-ARGM-GOL | R-ARGM-LOC | R-ARGM-MNR | R-ARGM-MOD | R-ARGM-PNC | R-ARGM-PRD | R-ARGM-PRP | R-ARGM-TMP) #REQUIRED
  start CDATA #REQUIRED
  end CDATA #REQUIRED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== propbank/propbank-frames/frames/exclude.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="exclude">
    <roleset id="exclude.01" name="exclude, except">
      <aliases>
        <alias pos="j">exclusive</alias>
        <alias pos="v">exclude</alias>
        <alias pos="n">exclusion</alias>
      </aliases>
      <roles>
        <role descr="agent, excluder" f="PAG" n="0">
          <rolelinks>
            <rolelink class="65" resource="VerbNet" version="UNK">agent</rolelink>
            <rolelink class="forbid-64.4-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
            <rolelink class="exclude-107.3-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
          </rolelinks>
        </role>
        <role descr="patient, thing excluded" f="PPT" n="1">
          <rolelinks>
            <rolelink class="65" resource="VerbNet" version="UNK">theme</rolelink>
            <rolelink class="forbid-64.4-1" resource="VerbNet" version="verbnet3.4">theme</rolelink>
            <rolelink class="exclude-107.3-1" resource="VerbNet" version="verbnet3.4">theme</rolelink>
          </rolelinks>
        </role>
        <role descr="excluded-from" f="VSP" n="2">
          <rolelinks>
            <rolelink class="65" resource="VerbNet" version="UNK">location</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        </usagenotes>
      <lexlinks>
        <lexlink class="Inclusion" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Exclude_member" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="exclude-107.3-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
        <lexlink class="forbid-64.4-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="exclude-v: discourse function, with (empty) arg0" src="">
        <text>*trace* Excluding one - time additions to profit in each year , earnings per share were $ 2.47 , up 7.4 % from $ 2.30 in fiscal 1988 .</text>
        <propbank>
          <rel relloc="1">Excluding</rel>
          <arg type="ARG0" start="?" end="?">*trace*</arg>
          <arg type="ARG1" start="2" end="10">one - time additions to profit in each year</arg>
        </propbank>
      </example>
      <example name="exclude-v: discourse function, no arg0" src="">
        <text>Still , the combined profit of Ford , Chrysler Corp. and General Motors Corp. fell 44 % to $ 1.02 billion from $ 1.83 billion a year earlier , excluding a one - time gain of $ 309 million at Chrysler from the sale of Mitsubishi Motors Corp. stock .</text>
        <propbank>
          <rel relloc="29">excluding</rel>
          <arg type="ARG1" start="30" end="48">a one - time gain of $ 309 million at Chrysler from the sale of Mitsubishi Motors Corp. stock</arg>
        </propbank>
      </example>
      <example name="exclude-v: real verbal, transitive" src="">
        <text>The figures exclude businesses now organized as American Express Information Services Co.</text>
        <propbank>
          <rel relloc="2">exclude</rel>
          <arg type="ARG0" start="0" end="1">The figures</arg>
          <arg type="ARG1" start="3" end="11">businesses now organized as American Express Information Services Co.</arg>
        </propbank>
      </example>
      <example name="exclude-v: with excluded-from" src="">
        <text>The federal appeals court held that the nominal damages and the failure to prove all claims did n't exclude the USFL from being reimbursed .</text>
        <propbank>
          <rel relloc="18">exclude</rel>
          <arg type="ARG0" start="6" end="15">the nominal damages and the failure to prove all claims</arg>
          <arg type="ARGM-NEG" start="17" end="17">n't</arg>
          <arg type="ARG1" start="19" end="20">the USFL</arg>
          <arg type="ARG2" start="21" end="23">from being reimbursed</arg>
        </propbank>
      </example>
      <example name="exclusion-n: Args 1 and 2" src="">
        <text>the exclusion of the company 's British sales from the current year 's figures</text>
        <propbank>
          <rel relloc="1">exclusion</rel>
          <arg type="ARG1" start="2" end="7">of the company 's British sales</arg>
          <arg type="ARG2" start="8" end="13">from the current year 's figures</arg>
        </propbank>
      </example>
      <example name="exclusion-n: args 1 and 2 again" src="">
        <text>the exclusion from elections of those charged with but not yet convicted of the relevant offences</text>
        <propbank>
          <rel relloc="1">exclusion</rel>
          <arg type="ARG2" start="2" end="3">from elections</arg>
          <arg type="ARG1" start="4" end="15">of those charged with but not yet convicted of the relevant offences</arg>
        </propbank>
      </example>
      <example name="exclusion-n: All args" src="">
        <text>His exclusion of his sister from the wedding party caused considerable family discord .</text>
        <propbank>
          <rel relloc="1">exclusion</rel>
          <arg type="ARG0" start="0" end="0">His</arg>
          <arg type="ARG1" start="2" end="4">of his sister</arg>
          <arg type="ARG2" start="5" end="8">from the wedding party</arg>
        </propbank>
      </example>
      <example name="exclusive-j: mutually exclusive" src="BOLT-7">
        <text>In fact , commodity housing market and government - regulated market are to a large extent , not mutually exclusive .</text>
        <propbank>
          <rel relloc="19">exclusive</rel>
          <arg type="ARGM-DIS" start="0" end="1">In fact</arg>
          <arg type="ARG0" start="3" end="10">commodity housing market and government - regulated market</arg>
          <arg type="ARGM-EXT" start="12" end="15">to a large extent</arg>
          <arg type="ARGM-NEG" start="17" end="17">not</arg>
          <arg type="ARG1" start="18" end="18">mutually</arg>
        </propbank>
      </example>
      <example name="exclusive-j: args 0, 1" src="BOLT-7">
        <text>Our room rate was exclusive of breakfast</text>
        <propbank>
          <rel relloc="4">exclusive</rel>
          <arg type="ARG0" start="0" end="2">Our room rate</arg>
          <arg type="ARG1" start="5" end="6">of breakfast</arg>
        </propbank>
      </example>
      <note>EXCLUDE-V NOTES: Frames file for 'exclude' based on sentences in financial subcorpus. Member of VNcls admit-65. No comparison.(from exclude.01-v)</note>
      <note>EXCLUSION-N NOTES: Based on sentences in nouns-00040.Comparison to 'exclude.01'. Vn class admit-65. Framed by Katie.(from exclusion.01-n)</note>
      <note>EXCLUSIVE-J NOTES: Automatically created by Julia as an aliasfile for unification.(from exclusive.01-j)</note>
    </roleset>
  </predicate>
  <predicate lemma="exclusive">
    <roleset id="exclusive.02" name="snobbish, reserved for a select elite group">
      <aliases>
        <alias pos="j">exclusive</alias>
      </aliases>
      <roles>
        <role descr="exclusive entity/location/organization" f="PAG" n="0"/>
        <role descr="elite group reserved for" f="PPT" n="1"/>
        <role descr="group excluded" f="VSP" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        </usagenotes>
      <lexlinks/>
      <example name="exclusive-j" src="">
        <text>The infinity pool was exclusive for guests who booked a room for overnight stay so the pool is n't overcrowded and you would have a little privacy ( although , there were occasional sneaks from " day - users " using the infinity pool ) .</text>
        <propbank>
          <rel relloc="4">exclusive</rel>
          <arg type="ARG0" start="0" end="2">The infinity pool</arg>
          <arg type="ARG1" start="5" end="13">for guests who booked a room for overnight stay</arg>
          <arg type="ARGM-ADV" start="14" end="44">so the pool is n't overcrowded and you would have a little privacy ( although , there were occasional sneaks from " day - users " using the infinity pool )</arg>
        </propbank>
      </example>
      <note>EXCLUSIVE-J NOTES: Split off from original 'exclusive-j' roleset by Julia for unification.</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/elapse.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="elapse">
    <roleset id="elapse.01" name="go by, as time">
      <aliases>
        <alias pos="v">elapse</alias>
      </aliases>
      <roles>
        <role descr="time gone by" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="one example" src="">
        <text>But the Beebes did n't come to that conclusion until time limits had elapsed for adding the adhesives maker as a defendant in the case , Ms. Adams said .</text>
        <propbank>
          <rel relloc="13">elapsed</rel>
          <arg type="ARG1" start="10" end="11">time limits</arg>
          <arg type="C-ARG1" start="14" end="24">for adding the adhesives maker as a defendant in the case</arg>
        </propbank>
      </example>
      <note>ELAPSE-V NOTES: Frames file for 'elapse' based on sentences in wsj. No Verbnet entry. (from elapse.01-v predicate notes)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/outcry.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="outcry">
    <roleset id="outcry.01" name="speaking out against">
      <aliases>
        <alias pos="n">outcry</alias>
      </aliases>
      <roles>
        <role descr="speaker" f="PAG" n="0"/>
        <role descr="spoken out against/about" f="PPT" n="1"/>
        <role descr="listener" f="GOL" n="2"/>
        <role descr="for what (if in addition to arg1)" f="CAU" n="3"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="args 1, 3" src="internet">
        <text>I do n't see the need for the outcry against him for stating an opinion ; instead , just form an opinion .</text>
        <propbank>
          <rel relloc="8">outcry</rel>
          <arg type="ARG1" start="9" end="10">against him</arg>
          <arg type="ARG3" start="11" end="14">for stating an opinion</arg>
        </propbank>
      </example>
      <example name="Arg2" src="internet">
        <text>... healing could begin with their outcry to a friend , family member , or an anonymous call to a hotline .</text>
        <propbank>
          <rel relloc="6">outcry</rel>
          <arg type="ARG2" start="7" end="20">to a friend , family member , or an anonymous call to a hotline</arg>
        </propbank>
      </example>
      <example name="args 0, 1, ADJ" src="BOLT">
        <text>Where 's the public outcry about Russian veto and unilateralism -LRB- a criticism routinely employed - rightly - against the United States when it vetoes resolutions on Israeli aggression -RRB- ?</text>
        <propbank>
          <rel relloc="4">outcry</rel>
          <arg type="ARG0" start="3" end="3">public</arg>
          <arg type="ARG1" start="5" end="9">about Russian veto and unilateralism</arg>
          <arg type="ARGM-ADJ" start="10" end="29">-LRB- a criticism routinely employed - rightly - against the United States when it vetoes resolutions on Israeli aggression -RRB-</arg>
        </propbank>
      </example>
      <note>OUTCRY-N NOTES: Added by Julia based on BOLT, WordNet. No VNcls. (from outcry.01-n)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/quilt.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="quilt">
    <roleset id="quilt.01" name="sew or stitch together">
      <aliases>
        <alias pos="v">quilt</alias>
        <alias pos="n">quilting</alias>
      </aliases>
      <roles>
        <role descr="quilter, agent" f="PAG" n="0"/>
        <role descr="material, things being quilted" f="PPT" n="1"/>
        <role descr="attached to if seperate from arg 1, quilted where" f="LOC" n="2"/>
        <role descr="product, end state" f="PRD" n="3"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="args 1 and 2" src="">
        <text>Organic French wool is quilted onto that</text>
        <propbank>
          <rel relloc="4">quilted</rel>
          <arg type="ARG1" start="0" end="2">Organic French wool</arg>
          <arg type="ARG2" start="5" end="6">onto that</arg>
        </propbank>
      </example>
      <example name="arg 3" src="">
        <text>After quilting the squares together ,</text>
        <propbank>
          <rel relloc="1">quilting</rel>
          <arg type="ARG1" start="2" end="3">the squares</arg>
          <arg type="ARG3" start="4" end="4">together</arg>
        </propbank>
      </example>
      <note>QUILTING-N NOTES: Based on Google data. Comparison with sew.01 and stitch.01. No VN or FN classes. Framed by Katie. (from quilting.01-n) </note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/dorm.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="dorm">
    <roleset id="dorm.01" name="staying in a dorm">
      <aliases>
        <alias pos="n">dorming</alias>
        <alias pos="v">dorm</alias>
      </aliases>
      <roles>
        <role descr="first entity staying in a dorm" f="PAG" n="0"/>
        <role descr="roommates" f="PPT" n="1"/>
        <role descr="location, dorm" f="LOC" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <example name="dorm-b: arg0" src="SMS">
        <text>I dormed with my best friend Freshman year</text>
        <propbank>
          <rel relloc="1">dormed</rel>
          <arg type="ARG0" start="0" end="0">I</arg>
          <arg type="ARG1" start="2" end="5">with my best friend</arg>
          <arg type="ARGM-TMP" start="6" end="7">Freshman year</arg>
        </propbank>
      </example>
      <note>DORMING-N NOTES: Added by Julia based on SMS. (from dorming.01-n)</note>
      <note>DORM-V NOTES: Automatically added alias.</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/rife.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="rife">
    <roleset id="rife.01" name="teeming, abundant">
      <aliases>
        <alias pos="j">rife</alias>
      </aliases>
      <roles>
        <role descr="location (perhaps abstract) teeming with arg2" f="LOC" n="1"/>
        <role descr="theme, abundant thing" f="PPT" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Abounding_with" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
      </lexlinks>
      <example name="both args" src="internet">
        <text>The history of technology is rife with stories and accounts of revolutionary approaches overturning the status quo .</text>
        <propbank>
          <rel relloc="5">rife</rel>
          <arg type="ARG1" start="0" end="3">The history of technology</arg>
          <arg type="ARG2" start="6" end="16">with stories and accounts of revolutionary approaches overturning the status quo</arg>
        </propbank>
      </example>
      <example name="arg2" src="BOLT-2,3">
        <text>Youth unemployment is rife at the moment so let 's get them piloting our aeroplanes .</text>
        <propbank>
          <rel relloc="3">rife</rel>
          <arg type="ARG2" start="0" end="1">Youth unemployment</arg>
          <arg type="ARGM-TMP" start="4" end="6">at the moment</arg>
        </propbank>
      </example>
      <note>RIFE-J NOTES: Added by Julia based on BOLT-2,3. (from rife.01-j)</note>
    </roleset>
  </predicate>
</frameset>
