=== propbank/propbank-frames/dtds/v3.4/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (r | p | v | n | j | l | x| m | d | f) #REQUIRED>


<!--
  pos = Part of Speech
  
  Can take the following values:

  r = Adverb
  p = Preposition
  v = Verb
  n = Noun
  j = Adjective
  l = (MISSING IDK)
  x = (MISSING IDK)
  m = (MISSING IDK)

-->


<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)
    
    #
    # Function tags for spatial arguments
    #
    SE1  first thing (UNVERIFIED)
    SE2  second thing (UNVERIFIED)    
    SE3  third thing (UNVERIFIED)
    SE4  fourth thing (UNVERIFIED)
    SE5  fifth thing (UNVERIFIED)    
    SE6  sixth thing (UNVERIFIED)    

    SCL  Scale (UNVERIFIED)

    DOM  Domain (UNVERIFIED)

    #
    # added from the spatial relations ontology
    #
    # https://docs.google.com/spreadsheets/d/1b_CJUsyGptG0RtZQ5qnuJjF0wHKyiahLJ83RhHRwgCE/edit#gid=154847108
    #
    ANC  anchor
    ANC1 first anchor
    ANC2 second anchor
    
    ANG angle

    AXS  axis
    AXSp perpendicular axis
    AXSc central axis
    AXS1 axis of spatial entity 1
    AXS2 axis of spatial entity 2

    WHL  whole spatial entity
    
    SEQ  sequence

    PSN  position
    #

    #
    # Not sure to which subgroup these balong
    #
    SET
    SRC  Source (UNVERIFIED)
    PRT
    



-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( ANC | ANC1 | ANC2 | ANG | DOM | AXS | AXSp | AXSc | AXS1 | AXS2 | WHL | SEQ | SET | SRC | PRT | SE1 | SE2 | SE3 | SE4 | SE5 | SE6 | SCL | PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!-- Adding a new element to distinguish propbank example from amr example (UNVERIFIED) -->
<!ELEMENT propbank (arg|rel|note)*>

<!ELEMENT amr (#PCDATA)>
<!ATTLIST amr
  version CDATA #IMPLIED>

<!ELEMENT example (note?, text, (propbank | amr | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  type ( ARG0 | ARG1 | ARG2 | ARG3 | ARG4 | ARG5 | ARG6 | ARG7 | C-ARG0 | C-ARG1 | C-ARG2 | C-ARG3 | C-ARG4 | C-ARG5 | C-ARG6 | C-ARG7 | R-ARG0 | R-ARG1 | R-ARG2 | R-ARG3 | R-ARG4 | R-ARG5 | R-ARG6 | R-ARG7 | ARGM-ADJ | ARGM-ADV | ARGM-CAU | ARGM-COM | ARGM-DIR | ARGM-DIS | ARGM-DSP | ARGM-EXT | ARGM-GOL | ARGM-LOC | ARGM-LVB | ARGM-MNR | ARGM-MOD | ARGM-NEG | ARGM-PNC | ARGM-PRD | ARGM-PRP | ARGM-PRR | ARGM-PRX | ARGM-REC | ARGM-TMP | ARGM-CXN | C-ARGM-ADJ | C-ARGM-ADV | C-ARGM-CAU | C-ARGM-COM | C-ARGM-DIR | C-ARGM-DIS | C-ARGM-DSP | C-ARGM-EXT | C-ARGM-LOC | C-ARGM-MNR | C-ARGM-MOD | C-ARGM-NEG | C-ARGM-PRP | C-ARGM-TMP | C-ARGM-CXN | R-ARGM-ADV | R-ARGM-CAU | R-ARGM-COM | R-ARGM-DIR | R-ARGM-EXT | R-ARGM-GOL | R-ARGM-LOC | R-ARGM-MNR | R-ARGM-MOD | R-ARGM-PNC | R-ARGM-PRD | R-ARGM-PRP | R-ARGM-TMP) #REQUIRED
  start CDATA #REQUIRED
  end CDATA #REQUIRED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== propbank/propbank-frames/frames/slap.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="slap">
    <roleset id="slap.01" name="hit with a flat object">
      <aliases>
        <alias pos="v">slap</alias>
      </aliases>
      <roles>
        <role descr="agent, hitter - animate only!" f="PAG" n="0">
          <rolelinks>
            <rolelink class="throw-17.1-1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">agent</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">cause</rolelink>
            <rolelink class="throw-17.1-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
          </rolelinks>
        </role>
        <role descr="thing hit" f="PPT" n="1">
          <rolelinks>
            <rolelink class="throw-17.1-1" resource="VerbNet" version="verbnet3.3">theme</rolelink>
            <rolelink class="bump-18.4-1" resource="VerbNet" version="verbnet3.3">theme</rolelink>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.3">patient</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">victim</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">body_part</rolelink>
            <rolelink class="throw-17.1-1" resource="VerbNet" version="verbnet3.4">theme</rolelink>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.4">patient</rolelink>
            <rolelink class="bump-18.4-1" resource="VerbNet" version="verbnet3.4">theme</rolelink>
          </rolelinks>
        </role>
        <role descr="instrument, thing hit by or with" f="MNR" n="2">
          <rolelinks>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.3">instrument</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">means</rolelink>
            <rolelink class="Cause_harm" resource="FrameNet" version="1.7">instrument</rolelink>
            <rolelink class="hit-18.1-1" resource="VerbNet" version="verbnet3.4">instrument</rolelink>
            <rolelink class="bump-18.4-1" resource="VerbNet" version="verbnet3.4">location</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Cause_impact" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Impact" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Cause_harm" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="throw-17.1-1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="hit-18.1-1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="bump-18.4-1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="Attack" confidence="0.1" resource="ERE" src="reo-expansion" version="rich"/>
        <lexlink class="slap-v.1" confidence="0.1" resource="onsense" src="annot-overlap" version="on5">8</lexlink>
        <lexlink class="throw-17.1-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
        <lexlink class="bump-18.4-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
        <lexlink class="hit-18.1-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="instrumental subject" src="">
        <text>London share prices closed sharply lower Friday in active trading after Chancellor of the Exchequer Nigel Lawson 's resignation slapped the market and Wall Street 's rapid initial sell - off knocked it down .</text>
        <propbank>
          <rel relloc="19">slapped</rel>
          <arg type="ARG2" start="11" end="18">Chancellor of the Exchequer Nigel Lawson 's resignation</arg>
          <arg type="ARG1" start="20" end="21">the market</arg>
        </propbank>
      </example>
      <example name="ARG0 and ARG2 and ARG1" src="ontonotes mz/sinorama/10/ectb_1021">
        <text>Once he came very close to cutting a finger clean off with a sickle , but he just slapped some cement mix -LRB- commonly regarded as a good disinfectant -RRB- on the wound and worked on through the pain .</text>
        <propbank>
          <rel relloc="18">slapped</rel>
          <arg type="ARG0" start="16" end="16">he</arg>
          <arg type="ARGM-ADV" start="17" end="17">just</arg>
          <arg type="ARG2" start="19" end="29">some cement mix -LRB- commonly regarded as a good disinfectant -RRB-</arg>
          <arg type="ARG1" start="30" end="32">on the wound</arg>
        </propbank>
      </example>
      <note>SLAP-V NOTES: Comparison with hit. Member of Vncls throw-17.1-1, bump-18.4-1, hit-18.1-1. Updated by Julia, 11/2010. (from slap.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/preach.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="preach">
    <roleset id="preach.01" name="to proclaim or advocate">
      <aliases>
        <alias pos="v">preach</alias>
        <alias pos="n">preaching</alias>
        <argalias arg="0" pos="n">preacher</argalias>
      </aliases>
      <roles>
        <role descr="preacher, agent" f="PAG" n="0">
          <rolelinks>
            <rolelink class="lecture-37.11-1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
            <rolelink class="transfer_mesg-37.1.1" resource="VerbNet" version="verbnet3.3">agent</rolelink>
            <rolelink class="Statement" resource="FrameNet" version="1.7">speaker</rolelink>
            <rolelink class="Speak_on_topic" resource="FrameNet" version="1.7">speaker</rolelink>
            <rolelink class="transfer_mesg-37.1.1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
            <rolelink class="lecture-37.11-1" resource="VerbNet" version="verbnet3.4">agent</rolelink>
          </rolelinks>
        </role>
        <role descr="utterance" f="PPT" n="1">
          <rolelinks>
            <rolelink class="lecture-37.11-1" resource="VerbNet" version="verbnet3.3">topic</rolelink>
            <rolelink class="transfer_mesg-37.1.1" resource="VerbNet" version="verbnet3.3">topic</rolelink>
            <rolelink class="Statement" resource="FrameNet" version="1.7">addressee</rolelink>
            <rolelink class="Statement" resource="FrameNet" version="1.7">message</rolelink>
            <rolelink class="Statement" resource="FrameNet" version="1.7">topic</rolelink>
            <rolelink class="Speak_on_topic" resource="FrameNet" version="1.7">topic</rolelink>
            <rolelink class="transfer_mesg-37.1.1" resource="VerbNet" version="verbnet3.4">topic</rolelink>
            <rolelink class="lecture-37.11-1" resource="VerbNet" version="verbnet3.4">topic</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Statement" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Speak_on_topic" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="lecture-37.11-1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="transfer_mesg-37.1.1" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="Contact.MediaStatement.Broadcast" confidence="0.1" resource="AidaOntology" src="reo-expansion" version="Jan2019"/>
        <lexlink class="Contact.PublicStatementInPerson.Broadcast" confidence="0.1" resource="AidaOntology" src="reo-expansion" version="Jan2019"/>
        <lexlink class="Broadcast" confidence="0.1" resource="ERE" src="reo-expansion" version="rich"/>
        <lexlink class="preach-v.2" confidence="0.1" resource="onsense" src="annot-overlap" version="on5">4</lexlink>
        <lexlink class="lecture-37.11-1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
        <lexlink class="transfer_mesg-37.1.1" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="preach-v: transitive" src="">
        <text>Others preach the gospel of buying only blue - chip growth stocks .</text>
        <propbank>
          <rel relloc="1">preach</rel>
          <arg type="ARG0" start="0" end="0">Others</arg>
          <arg type="ARG1" start="2" end="11">the gospel of buying only blue - chip growth stocks</arg>
        </propbank>
      </example>
      <example name="preach-v: preach about" src="">
        <text>Part of the problem is the tendency of all sitcoms , ever since the didactic days of Norman Lear , to preach about social issues .</text>
        <propbank>
          <rel relloc="21">preach</rel>
          <arg type="ARG0" start="8" end="9">all sitcoms</arg>
          <arg type="ARG1" start="22" end="24">about social issues</arg>
        </propbank>
      </example>
      <note>PREACH-V NOTES: Frames file for 'preach' based on survey of sentences in the WSJ corpus. (from preach.01-v predicate notes)</note>
    </roleset>
  </predicate>
</frameset>

=== propbank/propbank-frames/frames/storm.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="storm">
    <roleset id="storm.01" name="bad weather">
      <aliases>
        <alias pos="v">storm</alias>
      </aliases>
      <roles>
        <role descr="Cognate object, entity stormed e.g. cats and dogs, golf balls, rain itself" f="PPT" n="1">
          <rolelinks>
            <rolelink class="weather-57" resource="VerbNet" version="verbnet3.3">theme</rolelink>
            <rolelink class="weather-57" resource="VerbNet" version="verbnet3.4">theme</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Weather" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="weather-57" confidence="0.8" resource="VerbNet" src="manual+strict-conv" version="verbnet3.3"/>
        <lexlink class="weather-57" confidence="1.0" resource="VerbNet" src="manualchecks" version="verbnet3.4"/>
      </lexlinks>
      <example name="storm-v: stormy weather...." src="">
        <text>`` Wow , '' said John , `` it 's really storming outside . ''</text>
        <propbank>
          <rel relloc="11">storming</rel>
          <arg type="ARGM-MNR" start="10" end="10">really</arg>
          <arg type="ARGM-LOC" start="12" end="12">outside</arg>
        </propbank>
      </example>
      <note>STORM-V NOTES: Based on WSJ. Member of VNcls weather-57. (from storm.01-v)</note>
      <note>Don't tag weather "it". Unlikely that this will ever take args. (from storm.01-v)</note>
    </roleset>
    <roleset id="storm.02" name="move violently">
      <aliases>
        <alias pos="v">storm</alias>
      </aliases>
      <roles>
        <role descr="entity in motion" f="PAG" n="0">
          <rolelinks>
            <rolelink class="Self_motion" resource="FrameNet" version="1.7">self_mover</rolelink>
            <rolelink class="Attack" resource="FrameNet" version="1.7">victim</rolelink>
          </rolelinks>
        </role>
        <role descr="path" f="DIR" n="1">
          <rolelinks>
            <rolelink class="Self_motion" resource="FrameNet" version="1.7">goal</rolelink>
            <rolelink class="Self_motion" resource="FrameNet" version="1.7">path</rolelink>
            <rolelink class="Attack" resource="FrameNet" version="1.7">place</rolelink>
            <rolelink class="Attack" resource="FrameNet" version="1.7">path</rolelink>
          </rolelinks>
        </role>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
        <usage resource="PropBank" version="3.5" inuse="+"/>
        <usage resource="AMR" version="iSAT 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks>
        <lexlink class="Self_motion" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Attack" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7"/>
        <lexlink class="Movement.TransportPerson.SelfMotion" confidence="0.1" resource="AidaOntology" src="reo-expansion" version="Jan2019"/>
        <lexlink class="Transportperson" confidence="0.1" resource="ERE" src="reo-expansion" version="rich"/>
        <lexlink class="Attack" confidence="0.1" resource="ERE" src="reo-expansion" version="rich"/>
        <lexlink class="storm-v.2" confidence="0.1" resource="onsense" src="annot-overlap" version="on5">13</lexlink>
      </lexlinks>
      <example name="storm-v: sorta path-ish" src="">
        <text>Another described how tax - collection officials in Thanh Hoa province one night stormed through homes and confiscated rice from starving villagers .</text>
        <propbank>
          <rel relloc="13">stormed</rel>
          <arg type="ARG0" start="3" end="10">tax - collection officials in Thanh Hoa province</arg>
          <arg type="ARGM-TMP" start="11" end="12">one night</arg>
          <arg type="ARG1" start="14" end="15">through homes</arg>
        </propbank>
      </example>
      <example name="storm-v: definitely path, maybe different sense" src="">
        <text>The pillars of apartheid may be trembling in the rest of South Africa , with Johannesburg opening its public facilities to all races , blacks storming the all - white beaches of the Cape and the government releasing seven leaders of the banned African National Congress .</text>
        <propbank>
          <rel relloc="25">storming</rel>
          <arg type="ARG0" start="24" end="24">blacks</arg>
          <arg type="ARG1" start="26" end="33">the all - white beaches of the Cape</arg>
        </propbank>
      </example>
      <note>STORM-V NOTES: No Vncls. (from storm.02-v)</note>
    </roleset>
  </predicate>
</frameset>
